version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: assignment_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"


